---
kind: pipeline
name: default
type: docker

environment:
  VCS_REF: ${DRONE_COMMIT_REF}

steps:
  - name: v3.2.4
    image: plugins/docker
    environment:
      HELM_VERSION: v3.2.4
      OC_VERSION: 4.6
      KUBE_LATEST_VERSION: v1.18.3
    settings:
      username: 1995parham
      password:
        from_secret: docker_password
      repo: 1995parham/helm-kubectl-oc
      tags:
        - latest
        - 3.2.4
      build_args_from_env:
        - HELM_VERSION
        - VCS_REF
        - OC_VERSION
        - KUBE_LATEST_VERSION
