---
kind: pipeline
name: default
type: docker

steps:
  - name: docker
    image: plugins/docker
    settings:
      username: 1995parham
      password:
        from_secret: docker_password
      repo: 1995parham/helm-kubectl-oc
      tags: latest
